name: build-env

channels:
  - conda-forge

dependencies:
  - python=3.9
  - cmake>=3.20
  - ninja>=1.5
  - eigen
  - boost
  - boost-cpp
  - libboost
  - libboost-devel
  - libboost-headers
  - libboost-python
  - libboost-python-devel
  - pre-commit
